version: 2.1

orbs:
  node: circleci/node@7.2.0

jobs:
  code-quality:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
        pnpm-version: '10.18.2'
        install-pnpm: true
        node-version: lts
        use-nvm-cache: true

workflows:
  code-quality:
    jobs:
      - code-quality